package org.janelia.jacs2.model.jacsservice;

public enum JacsServiceEventTypes {
    CANCELED,
    COMPLETED,
    SUSPEND,
    TIMEOUT,
    CREATE_CHILD_SERVICE,
    CLUSTER_SUBMIT,
    CLUSTER_JOB_ERROR,
    FAILED,
    CREATED_RUNNING_SCRIPT,
    SCRIPT_CREATION_ERROR,
    START_PROCESS,
    START_PROCESS_ERROR,
    PROCESSING_ERROR,
    PROCESSING_COMPLETED,
    UPDATE_STATE
}
