version: 2
jobs:
  build:

    branches:
      only:
       - master
   
    working_directory: ~/jacs-compute

    docker:
      - image: circleci/openjdk:8u171-jdk

    environment:
      TERM: dumb

    steps:

      - checkout

      - restore_cache:
          keys: 
            - jacs-compute-c4-{{ checksum "build.gradle" }}
            - jacs-compute-c4
      
      - run: ./gradlew dependencies
      
      - save_cache:
          key: jacs-compute-c4-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle

      - run: ./gradlew --no-daemon installDist test

      - store_artifacts:
      	  path: build/reports/tests/test
	  destination: test-results

      - store_test_results:
          path: test-results

      
