version: 2
jobs:
  build:

    branches:
      only:
       - master
   
    working_directory: ~/jacs-compute

    docker:
      - image: circleci/openjdk:8u171-jdk

    environment:
      TERM: dumb

    steps:

      - checkout

      - restore_cache:
          keys: 
            - jacs-compute-c3-{{ checksum "build.gradle" }}
            - jacs-compute-c3
      
      - run: ./gradlew dependencies
      
      - save_cache:
          key: jacs-compute-c3-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle

      - run: ./gradlew --no-daemon installDist test

      - store_test_results:
          paths: 
            - jacs2-services/build/test-results/test
            - jacs2-commonweb/build/test-results/test
            - jacs2-asyncweb/build/test-results/test
            - jacs2-syncweb/build/test-results/test
      
